import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Hello from "@/components/Hello";
import ClientOnly from "@/components/ClientOnly";
import Altogether from "@/components/Altogether";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Hello />
          <Altogether />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
